### ISSUE TITLE
Simple snapshot testing is breaking tests

### ISSUE THREAD

**Issue by FerreiraRaphael** [mfrachet/rn-placeholder#63]
I have snapshot tests for my components, in a simple test as this one
```javascript
describe('Components - LoadingList', () => {
    it('renders', () => {
        expect(renderer.create(
            <LoadingList />
        )).toMatchSnapshot();
    });
});
```
this component `LoadingList` imports `rn-placeholder`.
it fails with the following message:
```javascript
 FAIL  app/views/LoadingList/__tests__/LoadingList.test.js
  ● Test suite failed to run

    /Users/raphael/Mudano/mobile-v2/node_modules/rn-placeh
older/index.js:1
    ({"Object.<anonymous>":function(module,exports,require
,__dirname,__filename,global,jest){import Placeholder from './src/placeholder';
                                          ^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      1 | import React from 'react';
      2 | import { Animated } from 'react-native';
    > 3 | import Placeholder from 'rn-placeholder';
        |        ^
      4 |
      5 | // Config & Styling
      6 | import AppConfig from 'app/config';

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (app/views/LoadingList/LoadingCard.js:3:57)
```

when I remove `rn-placeholder` the tests works fine.

this is my jest config:
```javascript
"jest": {
    "setupTestFrameworkScriptFile": "<rootDir>/test/setupTest.js",
    "preset": "react-native",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    }
  },
```

Can you guys help-me with this ?

**Comment by mfrachet** [comment]
Like `react-navigation`, can try by adding these lines?

```json
"jest": {
    "transformIgnorePatterns": [
      "<rootDir>/node_modules/rn-placeholder)"
    ],
  },
```

**Comment by mfrachet** [comment]
I close this, feel free to reopen if needed

**Comment by FerreiraRaphael** [comment]
Hello @mfrachet, could you please reopen this issue, I added this transformIgnorePatterns, and it didn't seem to work 😢

**Comment by FerreiraRaphael** [comment]
current jest config

```javascript
"jest": {
    "setupTestFrameworkScriptFile": "<rootDir>/test/setupTest.js",
    "preset": "react-native",
    "transformIgnorePatterns": [
        "<rootDir>/node_modules/rn-placeholder"
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    }
  },
```
